name: Cancelled Flight Prediction
description: Predicting flight cancellations
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 2.0
date: "2022-03-29"

environment_variables:
  STORAGE_MODE:
    default: local
    description: >-
      This variable designates whether the project is built from scratch ('external') or from the preprocessed dataset included
      in the repo ('local'). If this variable is set to 'external', the user must have access to the external storage configured 
      on the CML workspace's environment, and the project setup tasks will download, process, and store ~20GB of raw data to the
      storage location specificed below.
  DATA_LOCATION:
    default: data/flight_data
    description: >-
      Relative path that will be used to store the data used for this prototype.
      This should be a location you have write access to, and which is suitable for non-production data.
  HIVE_DATABASE:
    default: default
    description: >-
      Name of the Hive database that will be used to create the Hive table used for this prototype.
      This should be a Hive database you have write access to, and which is suitable for non-production data.
  HIVE_TABLE:
    default: flight_prototype
    description: >-
      Name of the Hive table that will be created and populated with the data used for this prototype.
      If the table already exists, the prototype will assume it already contains the data for this prototype.

feature_dependencies:
  - model_metrics

runtimes:
  - editor: Workbench
    kernel: Python 3.7
    edition: Standard

tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: code/0_bootstrap.py
    arguments: None
    short_summary: Job to install dependencies and download training data.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_deps
    cpu: 1
    memory: 2
    short_summary: Running install dependencies training job.
    long_summary: >-
      Running the job to install dependencies.

  - type: create_job
    name: Ingest data
    entity_label: ingest_data
    script: code/1_data_ingest.py
    arguments: None
    short_summary: Job to ingest raw data files
    long_summary: >-
      This script will only run if STORAGE_MODE is set to external
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: ingest_data
    cpu: 1
    memory: 2
    short_summary: Running job to ingest raw data files

#  - type: create_job
#    name: Preprocess data
#    entity_label: preprocess_data
#    script: code/3_data_processing.py
#    arguments: None
#    short_summary: Job to process raw data files
#    long_summary: >-
#      This script will only run if STORAGE_MODE is set to external
#    environment:
#      TASK_TYPE: CREATE/RUN_JOB

#  - type: run_job
#    entity_label: preprocess_data
#    cpu: 4
#    memory: 12
#    short_summary: Running job to process raw data files

  - type: create_job
    name: Train Flight Delay Prediction Model
    entity_label: train_model
    script: code/5_model_train.py
    arguments: None
    short_summary: Job to train model.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: train_model
    cpu: 2
    memory: 8
    short_summary: Run model training job.
    long_summary: >-
      Running the job to train models.

  - type: create_model
    name: Flight Delay Prediction Model Endpoint
    entity_label: flight_model
    description: This model api endpoint predicts flight delays
    short_summary: Create the flight delay prediction model api endpoint
    access_key_environment_variable: SHTM_ACCESS_KEY
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Flight Delay Prediction Model API Endpoint
    entity_label: flight_model
    comment: Build flight prediction model
    examples:
      - request: { "feature": "US,DCA,BOS,1,16" }
        response: 1
    target_file_path: code/6_model_serve.py
    target_function_name: predict_cancelled
    environment_variables:
      TASK_TYPE: CREATE/BUILD/DEPLOY_MODEL

  - type: deploy_model
    name: flight_prediction_model
    entity_label: flight_model
    cpu: 1
    gpu: 0
    environment_variables:
      TASK_TYPE: CREATE/BUILD/DEPLOY_MODEL

  - type: start_application
    name: Application to serve flight prediction front end app UI
    subdomain: flight
    script: code/7_application.py
    environment_variables:
      TASK_TYPE: START_APPLICATION