name: Cancelled Flight Prediction
description: Predicting flight cancellations. This AMP use data connections and the Exploratory Data Science and Visualization capabilities. 
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 3.0
date: "2022-07-22"

environment_variables:
  STORAGE_MODE:
    default: local
    description: >-
      Designate whether the project uses external data ('external') or the preprocessed dataset included
      in the repo ('local'). 
      NOTE: `EXTERNAL` MODE REQUIRES CML DATA SERVICES and the user must configure the env variables below. 
      CDSW USERS MUST CHOSE 'LOCAL' MODE. 
  SPARK_CONNECTION_NAME:
    default: na
    description: >-
      Required when STORAGE_MODE=external. 
      This variable sets the Spark Connection name in the Workspace.
  DW_DATABASE:
    default: airlines
    description: >-
      Required when STORAGE_MODE=external. 
      Name of the database that the flight data is available in.
  DW_TABLE:
    default: flights
    description: >-
      Required when STORAGE_MODE=external. 
      Name of data warehouse table that holds the flights data. 
      The prototype supports both Hive and Iceberg table formats. 
      NOTE: Select Spark 2.x for Hive, and Spark 3.x for Iceberg. 
  USE_PREBUILT_MODEL:
    default: yes
    description: >-
      Deploy a pre-trained flight cancellation model.
      If set to 'no' a new model will be trained.

feature_dependencies:
  - model_metrics

runtimes:
  - editor: Workbench
    kernel: Python 3.9
    edition: Standard
    addons: ["Spark 3.2.3 - CDE 1.19 - HOTFIX-2"]


tasks:
  - type: create_job
    name: Install dependencies
    entity_label: install_deps
    script: code/0_bootstrap.py
    arguments: None
    short_summary: Job to install dependencies.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: install_deps
    cpu: 1
    memory: 2
    short_summary: Running install dependencies job.
    long_summary: >-
      Running the job to install dependencies.

  - type: create_job
    name: Preprocess data
    entity_label: preprocess_data
    script: code/3_data_processing.py
    arguments: None
    short_summary: Job to process raw data files
    long_summary: >-
      This script will only run if STORAGE_MODE is set to external
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: preprocess_data
    cpu: 4
    memory: 12
    short_summary: Running job to process raw data files

  - type: create_job
    name: Train Flight Delay Prediction Model
    entity_label: train_model
    script: code/5_model_train.py
    arguments: None
    short_summary: Job to train model.
    environment:
      TASK_TYPE: CREATE/RUN_JOB

  - type: run_job
    entity_label: train_model
    cpu: 4
    memory: 8
    short_summary: Run model training job.
    long_summary: >-
      Running the job to train models.

  - type: create_model
    name: Flight Delay Prediction Model Endpoint
    entity_label: flight_model
    description: This model api endpoint predicts flight delays
    short_summary: Create the flight delay prediction model api endpoint
    access_key_environment_variable: SHTM_ACCESS_KEY
    default_replication_policy:
      type: fixed
      num_replicas: 1

  - type: build_model
    name: Flight Delay Prediction Model API Endpoint
    entity_label: flight_model
    comment: Build flight prediction model
    examples:
      - request: { "feature": "US,DCA,BOS,1,16" }
        response: 1
    target_file_path: code/6_model_serve.py
    target_function_name: predict_cancelled
    environment_variables:
      TASK_TYPE: CREATE/BUILD/DEPLOY_MODEL

  - type: deploy_model
    name: flight_prediction_model
    entity_label: flight_model
    cpu: 1
    gpu: 0
    environment_variables:
      TASK_TYPE: CREATE/BUILD/DEPLOY_MODEL

  - type: start_application
    name: Application to serve flight prediction front end app UI
    subdomain: flight
    script: code/7_application.py
    environment_variables:
      TASK_TYPE: START_APPLICATION
